# Generated by Django 4.0.6 on 2022-07-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('species', models.CharField(default='', max_length=50, verbose_name='종')),
                ('period', models.IntegerField(default=7, verbose_name='물주기 기간')),
                ('last_water_date', models.DateTimeField(blank=True, null=True, verbose_name='마지막으로 물 준 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
