# Generated by Django 4.0.6 on 2022-07-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_remove_plant_last_water_date_waterlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterlog',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='waterlog',
            name='water_date',
        ),
        migrations.AlterField(
            model_name='waterlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='물 준 시간'),
        ),
    ]
